### ISSUE TITLE
deprecation warning when using ember 1.13.9

### ISSUE THREAD

**Issue by tsing80** [jmurphyau/ember-get-helper#14]
The following deprecation warning is shown when using ember 1.13.9:

```
DEPRECATION: Using Ember.HTMLBars._registerHelper is deprecated. Helpers (even dashless ones) are automatically resolved. [deprecation id: ember-htmlbars.register-helper]
```

**Comment by dschmidt** [comment]
Wouldn't it be enough to simply copy over the registerHelper wrapper from ember-truth-helpers? 

https://github.com/jmurphyau/ember-truth-helpers/blob/master/addon/utils/register-helper.js

**Comment by dschmidt** [comment]
Nevermind, I didn't look closely enough to see Ember.Helper was already checked. I used to see this warning too, but now it's gone anyway. Maybe I was using some older version.

@tsing80 are you sure you are on the latest release?
