### ISSUE TITLE
 Error: Could not find module `ember-get-helpers/helpers/get` imported from `test-app/helpers/get`

### ISSUE THREAD

**Issue by jcope2013** [jmurphyau/ember-get-helper#17]
the helper registration seems to not be working properly now, I am on ember 1.13.10

related to this PR https://github.com/jmurphyau/ember-get-helper/pull/16

**Comment by Fed03** [comment]
:+1:

**Comment by balinterdi** [comment]
I have the latest version (1.0.2) of the addon, I'm on Ember 1.13.10 and I still get this error.

**Comment by Fed03** [comment]
@balinterdi for now I'm using v1.0.1 that works with 1.13.10

**Comment by balinterdi** [comment]
Thank you, Federico, that works!

**Comment by jmurphyau** [comment]
I'll get to this as soon as I can

**Comment by Fed03** [comment]
@jmurphyau could you please publish the new version on npm? thank you!
