### ISSUE TITLE
Wrong deprecation warning using Ember 1.13.10

### ISSUE THREAD

**Issue by sly7-7** [jmurphyau/ember-get-helper#19]
With Ember 1.13.10, the helper beeing used is the glimmerHelper, but it throws this deprecation warning: 

`DEPRECATION: ember-get-helper has been included in Ember 2.0. Use of this package is deprecated` 

I wonder if this message could just be removed.
Unless I'm missing something, [this commit](https://github.com/jmurphyau/ember-get-helper/commit/718322682921772e717b37d5eaad3c7538625b30) the addon will just be a no op in 2.0, so the message would not be displayed anyway.

**Comment by jamesarosen** [comment]
I agree. It looks like 1.0.4 could do away with this deprecation warning for 1.13. Users would only see it when they upgrade to 2.0.
