### ISSUE TITLE
Act as a polyfill

### ISSUE THREAD

**Issue by miguelcobain** [jmurphyau/ember-get-helper#22]
I think this project should behave a bit differently regarding ember versions.
We should follow [ember-new-computed](https://github.com/rwjblue/ember-new-computed)'s example and behave like:
> For versions prior to 1.12.0-beta.1 this addon will allow usage of the new syntax by polyfilling but as of Ember 1.12.0-beta.1 *a polyfill is not needed and the internal implementation of Ember.computed is used*.

This is extremely useful for addon developers that want to use the get helper in their addons but still want to maintain the compatibility with Ember 1.13 users.

**Comment by rwjblue** [comment]
Yeah, I believe I was a tad over-zealous when adding that warning in https://github.com/jmurphyau/ember-get-helper/pull/9.  I'm perfectly happy to have it removed when ember-get-helper is included by an addon, but I think the warning is still good for apps that have moved to 2.0.0.  

My suggestion (needs to be tested with addon and apps) would be:

```
  treeFor: function() {
    if (this._checkerForEmber.lt('2.0.0-beta.1')) {
      return this._super.treeFor.apply(this, arguments);
    } else if (this.parent === this.project) { 
      // this means that we are being included directly in an app
      // and not as a nested addon
      console.warn('ember-get-helper is not required for Ember 2.0.0 and later (a default `get` helper is included with Ember), please remove from your `package.json`.');
    }
  }
```
